version: '3'

services:
  init-backend:
    build:
      context: .
    volumes:
      - ./:/app/src/
    networks:
      - internal
    working_dir: /app/src/
    entrypoint: ./init.sh

  frontend:
    image: node:10-alpine
    restart: always
    volumes:
      - ./frontend:/app/src/
    networks:
      - internal
    working_dir: /app/src/
    entrypoint: sh -c 'npm install && npm run serve'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - internal
    volumes:
      - ./:/app/src/
    stdin_open: true
    tty: true
    working_dir: /app/src/
    entrypoint: python manage.py runserver 0.0.0.0:8000

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8000:80


networks:
  internal:
    external: false

