# Generated by Django 2.1.7 on 2019-03-16 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(help_text='10 или 12 цифр', max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^([0-9]{10}|[0-9]{12})$')], verbose_name='ИНН'),
        ),
    ]
